spring:
  application:
    name: Kindle Proxy

server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

settings:
  font-size-scale: ${SETTINGS_DEFAULT_FONT_SIZE:12, 16, 20, 24, 28, 32, 36, 40, 44, 48}
  default:
    font-size: ${SETTINGS_DEFAULT_FONT_SIZE:24}

proxy:
  calibration:
    cache-directory: calibration-cache
  royal-road:
    favorites-user-id: ${ROYAL_ROAD_PROFILE:}