spring:
  application:
    name: Kindle Proxy

server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

proxy:
  calibration:
    cache-directory: calibration-cache
  royal-road:
    favorites-user-id: ${ROYAL_ROAD_PROFILE:}