spring:
  application:
    name: Kindle Proxy

server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

settings:
  default:
    font-size: ${SETTINGS_DEFAULT_FONT_SIZE:36}

proxy:
  calibration:
    cache-directory: calibration-cache
  royal-road:
    favorites-user-id: ${ROYAL_ROAD_PROFILE:}